baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'bridget'

[taxonomies]
  tag = "tags"
  category = "categories"
  keyword = "keywords"
  year = "year"
  equipment = "equipment"
